### ISSUE TITLE
Error di termux

### ISSUE THREAD

**Issue by MuhammadRestu999** [MaulanaRyM/Netsh-wlan#1]
Awokawokawok

Traceback (most recent call last):
  File "netsh.py", line 4, in <module>
    exec(base64.b64decode('IyEvdXNyL1B5dGhvbgojUmVtYWtlIEJ5IE1hdWxhbmFSeU0KCmltcG9ydCBzdWJwcm9jZXNzCgpwcmludCAoJyAgIF8gICBfICAgXyAgIF8gICBfICAgICBfICAgXyAgIF8gICBfICAgICBfICAgXyAgIF8gICBfICAnKQpwcmludCAoJyAgLyBcIC8gXCAvIFwgLyBcIC8gXCAgIC8gXCAvIFwgLyBcIC8gXCAgIC8gXCAvIFwgLyBcIC8gXCAnKQpwcmludCAoJyAoIE4gfCBFIHwgVCB8IFMgfCBIICkgKCBXIHwgTCB8IEEgKSBOICkgKCBTIHwgSCB8IE8gfCBXICknKQpwcmludCAoJyAgXF8vIFxfLyBcXy8gXF8vIFxfLyAgIFxfLyBcXy8gXF8vIFxfLyAgIFxfLyBcXy8gXF8vIFxfLyAnKQpwcmludCAoJyAgICAgICAgICAgICAgICAgICA8Q3JlYXRlZCBCeSBNci55TT4gICAgICAgICAgICAgICAgICAgICAnKQpwcmludApyYXdfaW5wdXQoIlByZXNzIEVudGVyIFRvIENvbnRpbnVlLi4uIikKCmRhdGEgPSBzdWJwcm9jZXNzLmNoZWNrX291dHB1dChbJ25ldHNoJywgJ3dsYW4nLCAnc2hvdycsICdwcm9maWxlcyddKS5kZWNvZGUoJ3V0Zi04JywgZXJyb3JzPSJiYWNrc2xhc2hyZXBsYWNlIikuc3BsaXQoJ1xuJykKcHJvZmlsZXMgPSBbaS5zcGxpdCgiOiIpWzFdWzE6LTFdIGZvciBpIGluIGRhdGEgaWYgIkFsbCBVc2VyIFByb2ZpbGUiIGluIGldCmZvciBpIGluIHByb2ZpbGVzOgogICAgdHJ5OgogICAgICAgIHJlc3VsdHMgPSBzdWJwcm9jZXNzLmNoZWNrX291dHB1dChbJ25ldHNoJywgJ3dsYW4nLCAnc2hvdycsICdwcm9maWxlJywgaSwgJ2tleT1jbGVhciddKS5kZWNvZGUoJ3V0Zi04JywgZXJyb3JzPSJiYWNrc2xhc2hyZXBsYWNlIikuc3BsaXQoJ1xuJykKICAgICAgICByZXN1bHRzID0gW2Iuc3BsaXQoIjoiKVsxXVsxOi0xXSBmb3IgYiBpbiByZXN1bHRzIGlmICJLZXkgQ29udGVudCIgaW4gYl0KICAgICAgICB0cnk6CiAgICAgICAgICAgIHByaW50ICgiezo8MzB9fCAgezo8fSIuZm9ybWF0KGksIHJlc3VsdHNbMF0pKQogICAgICAgIGV4Y2VwdCBJbmRleEVycm9yOgogICAgICAgICAgICBwcmludCAoIns6PDMwfXwgIHs6PH0iLmZvcm1hdChpLCAiIikpCiAgICBleGNlcHQgc3VicHJvY2Vzcy5DYWxsZWRQcm9jZXNzRXJyb3I6CiAgICAgICAgcHJpbnQgKCJ7OjwzMH18ICB7Ojx9Ii5mb3JtYXQoaSwgIkVOQ09ESU5HIEVSUk9SIikpCmlucHV0KCIiKQ=='))
  File "<string>", line 14, in <module>
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/data/data/com.termux/files/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by MuhammadRestu999** [comment]
Cuma info bang :v
